### ISSUE TITLE
Feature Request: Disable Switch in KSP settings for mod

### ISSUE THREAD

**Issue by Jacke4913** [linuxgurugamer/CorrectCoL#1]
To aid switching between building aircraft (which this helps) and rockets (for which this only seems to be confusing), could a switch be added to the in-game configuration to disable this mod?

**Comment by linuxgurugamer** [comment]
How about only having it active in the SPH? and not in the VAB?

**Comment by Jacke4913** [comment]
I thought about that, but that then considers constraining aircraft to the SPH and rockets to the VAB.  A switch under control of the player gives flexibility.  Best for the on/off switch would be an icon control on the App Launcher, but I think a switch in the config settings would be easier.

**Comment by linuxgurugamer** [comment]
It's not a matter of easier, either is easy.  It's a matter of usage.  If it's in the config settings, it would be awkward to use

**Comment by Jacke4913** [comment]
Good point about usage.  I also clarified my feature request in this post in the forum topic.

https://forum.kerbalspaceprogram.com/index.php?/topic/160231-13-correctcol-stock-aerodynamics-design-aid-continued/&tab=comments#comment-3162162
